# Generated by Django 4.0.1 on 2022-02-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
