# Generated by Django 4.0.1 on 2022-03-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='viable',
            field=models.BooleanField(default=False),
        ),
    ]
