# Generated by Django 4.0.1 on 2022-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0002_timeslot_viable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['section', 'last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='section',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='section',
            field=models.ManyToManyField(to='slotter.Section'),
        ),
    ]
