# Generated by Django 4.0.1 on 2022-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0002_timeslot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=models.IntegerField(default=50),
        ),
    ]
