# Generated by Django 4.0.1 on 2022-04-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0003_alter_student_options_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pronouns',
            field=models.CharField(choices=[('NS', 'Not Specified'), ('NB', 'they, them, theirs'), ('F', 'she, her, hers'), ('M', 'he, him, him'), ('O', 'Other')], default='NS', max_length=2),
        ),
    ]
