# Generated by Django 4.0.1 on 2022-02-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0003_alter_timeslot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='weekday',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=models.IntegerField(default=2),
        ),
    ]
