# Generated by Django 4.0.1 on 2022-02-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0004_timeslot_weekday_alter_timeslot_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['weekday', 'start_time']},
        ),
    ]
