# Generated by Django 4.0.1 on 2022-05-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0004_student_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='pronouns',
            field=models.CharField(choices=[('NS', 'Not specified'), ('NB', 'they, them, theirs'), ('F', 'she, her, hers'), ('M', 'he, him, his'), ('PNS', 'Prefer not to specify'), ('O', 'Other')], default='NS', max_length=3),
        ),
    ]
