# Generated by Django 4.0.1 on 2022-05-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0005_section_instructor_alter_student_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_days',
            field=models.CharField(choices=[('MW', 'Mondays and Wednesdays'), ('TR', 'Tuesdays and Thursdays')], default='MW', max_length=3),
        ),
    ]
