# Generated by Django 4.0.1 on 2022-02-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0005_alter_timeslot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday')], default='1', max_length=2),
        ),
    ]
