# Generated by Django 4.0.1 on 2022-02-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0006_alter_timeslot_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0, max_length=2),
        ),
    ]
