# Generated by Django 4.0.1 on 2022-05-07 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0006_section_class_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='class_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='class_days',
            field=models.CharField(choices=[('MW', 'MW'), ('TR', 'TR')], default='MW', max_length=3),
        ),
    ]
