# Generated by Django 4.0.1 on 2022-02-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0008_alter_timeslot_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='viable',
            field=models.BooleanField(default=False),
        ),
    ]
