# Generated by Django 4.0.1 on 2022-06-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0008_alter_section_class_days_timeslot_combos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeslot_Combos',
        ),
    ]
