# Generated by Django 4.0.1 on 2022-03-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0009_remove_timeslot_day_timeslot_viable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
