# Generated by Django 4.0.1 on 2022-06-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0009_delete_timeslot_combos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeslotCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='slotter.section')),
                ('timeslots', models.ManyToManyField(to='slotter.Timeslot')),
            ],
        ),
    ]
