# Generated by Django 4.0.1 on 2022-06-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0010_timeslotcombo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeslotCombo',
        ),
    ]
