# Generated by Django 4.0.1 on 2022-06-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0012_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='seminar_weeks',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
    ]
