# Generated by Django 4.0.1 on 2022-06-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0013_section_seminar_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='seminar_weeks',
        ),
    ]
