# Generated by Django 4.0.1 on 2022-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0014_remove_section_seminar_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='seminar_weeks',
            field=models.CharField(default='1, 2, 3', max_length=7),
        ),
    ]
