# Generated by Django 4.0.1 on 2022-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0015_section_seminar_weeks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combination',
            options={'ordering': ['section']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021)], default=2022),
        ),
    ]
