# Generated by Django 4.0.1 on 2022-03-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0015_alter_timeslot_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='section',
        ),
    ]
