# Generated by Django 4.0.1 on 2022-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0016_alter_combination_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='quarter',
            field=models.CharField(choices=[('AU', 'Autumn'), ('WI', 'Winter'), ('SP', 'Spring')], default='Autumn', max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2022),
        ),
    ]
