# Generated by Django 4.0.1 on 2022-07-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0017_section_quarter_alter_section_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='quarter',
        ),
    ]
