# Generated by Django 4.0.1 on 2022-07-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0018_remove_section_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='quarter',
            field=models.IntegerField(choices=[(0, 'Summer'), (1, 'Autumn'), (2, 'Winter'), (3, 'Spring')], default=1),
        ),
    ]
