# Generated by Django 4.0.1 on 2022-11-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0021_alter_section_instructor_alter_section_spreadsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='spreadsheet',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
