# Generated by Django 4.0.1 on 2023-04-07 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotter', '0022_alter_section_spreadsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='assigned_students_breakdown',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='spreadsheet',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023),
        ),
    ]
